spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: poc
    password: poc123

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
